services:
  # MITA Production Backend Service
  - type: web
    name: mita-production
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python start_optimized.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromService:
          type: web
          name: mita-production
          property: port
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      # Secrets - These need to be set in Render Dashboard
      - key: SECRET_KEY
        sync: false  # Will be set manually in dashboard
      - key: JWT_SECRET
        sync: false  # Will be set manually in dashboard
      - key: DATABASE_URL
        sync: false  # Will be set manually in dashboard
      - key: OPENAI_API_KEY
        sync: false  # Will be set manually in dashboard
      # Redis Configuration - External Provider (Fallback to no Redis if not configured)
      - key: REDIS_URL
        value: ""  # Empty string will disable Redis gracefully
      - key: UPSTASH_REDIS_URL
        sync: false  # Set manually in Render dashboard - Upstash primary
      - key: REDIS_MAX_CONNECTIONS
        value: 20
      - key: REDIS_TIMEOUT
        value: 30
      - key: REDIS_RETRY_ON_TIMEOUT
        value: true
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: SENTRY_DSN
        sync: false
      - key: FIREBASE_JSON
        sync: false

databases:
  # PostgreSQL Database for Production
  - name: mita-production-db
    plan: starter
    databaseName: mita_production
    user: mita_user
    region: oregon

# Note: Redis will be provided by external service (Upstash)
# No local Redis database needed - using cloud Redis for high availability