apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mita.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mita.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database connection string (base64 encoded)
  database-url: {{ .Values.database.url | b64enc | quote }}
  
  # Redis connection string (base64 encoded)
  redis-url: {{ .Values.redis.url | b64enc | quote }}
  
  # JWT Secrets (base64 encoded)
  jwt-secret: {{ required "JWT secret is required" .Values.secrets.jwtSecret | b64enc | quote }}
  jwt-previous-secret: {{ .Values.secrets.jwtPreviousSecret | default "" | b64enc | quote }}
  
  # Application secret key (base64 encoded)
  secret-key: {{ required "Secret key is required" .Values.secrets.secretKey | b64enc | quote }}
  
  # External service API keys (base64 encoded)
  openai-api-key: {{ required "OpenAI API key is required" .Values.secrets.openaiApiKey | b64enc | quote }}
  
  # Optional secrets
  {{- if .Values.secrets.sentryDsn }}
  sentry-dsn: {{ .Values.secrets.sentryDsn | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.appStoreSharedSecret }}
  appstore-shared-secret: {{ .Values.secrets.appStoreSharedSecret | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.smtpPassword }}
  smtp-password: {{ .Values.secrets.smtpPassword | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.apnsKey }}
  apns-key: {{ .Values.secrets.apnsKey | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.apnsKeyId }}
  apns-key-id: {{ .Values.secrets.apnsKeyId | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secrets.apnsTeamId }}
  apns-team-id: {{ .Values.secrets.apnsTeamId | b64enc | quote }}
  {{- end }}

---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mita.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mita.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  # Application configuration
  ENVIRONMENT: {{ .Values.environment | quote }}
  DEBUG: {{ .Values.debug | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  
  # Monitoring configuration
  PROMETHEUS_MULTIPROC_DIR: "/tmp/prometheus_multiproc"
  
  # Logging configuration
  LOG_FORMAT: {{ .Values.logging.format | quote }}
  
  # CORS configuration
  ALLOWED_ORIGINS: {{ join "," .Values.security.allowedOrigins | quote }}
  
  # App Store configuration
  APNS_TOPIC: "com.mita.finance"
  APNS_USE_SANDBOX: {{ .Values.security.apnsUseSandbox | quote }}
  
  # SMTP configuration
  SMTP_HOST: {{ .Values.smtp.host | default "smtp.sendgrid.net" | quote }}
  SMTP_PORT: {{ .Values.smtp.port | default "587" | quote }}
  SMTP_FROM: {{ .Values.smtp.from | default "noreply@mita.finance" | quote }}
{{- end }}