# New York State Economic Profile
# Enhanced with comprehensive regional economic data for dynamic thresholds

currency: USD
region_code: US-NY  
region_name: New York State
cost_of_living_adjustment: 1.35  # 35% higher than national average
median_household_income: 78000   # 2024 NY median
poverty_level: 15060            # Federal poverty guideline 2024

# Economically justified 5-tier thresholds (annual income)
# Adjusted for NY cost of living and economic conditions
class_thresholds:
  low: 48600             # ~62% of NY median household income
  lower_middle: 77760    # ~100% of NY median household income  
  middle: 116640         # ~150% of NY median household income
  upper_middle: 194400   # ~249% of NY median household income
  # high: above upper_middle threshold

# Comprehensive regional economic factors
economic_factors:
  housing_cost_ratio: 0.38        # NY average housing cost % of income
  tax_burden: 0.12                # State + federal effective rate
  inflation_adjustment: 1.06      # Annual inflation factor
  unemployment_rate: 0.041        # NY unemployment rate
  job_growth_rate: 0.015          # Annual job growth
  cost_of_living_index: 1.35      # Relative to US average
  housing_market_factor: 1.45     # Housing cost multiplier
  transportation_cost_factor: 1.25 # Public transit costs
  healthcare_cost_factor: 1.15    # Healthcare cost premium

# Regional spending pattern modifiers
regional_spending_patterns:
  dining_out_frequency_multiplier: 1.4  # New Yorkers dine out more
  transportation_public_usage: 0.65     # High public transit usage
  housing_ownership_rate: 0.54          # Lower homeownership
  cultural_entertainment_premium: 1.6   # Higher entertainment costs

mandatory_categories: [housing, utilities, healthcare, debts, insurance, taxes, transportation]

seasonal_factors:
  winter:
    utilities: 1.25      # Cold weather heating costs
    clothing: 1.2        # Winter clothing needs
    transport: 1.1       # Weather-related transport costs
  summer:
    travel: 1.3          # Summer vacation season
    utilities: 0.8       # Lower heating costs
    entertainment: 1.15  # Outdoor activities

# Tier-specific budget allocations optimized for NY economics
classes:
  low:
    housing: 0.45          # High due to NY housing costs
    food: 0.14             # Efficient food spending
    transport: 0.12        # Public transit focus
    utilities: 0.08
    healthcare: 0.06
    savings: 0.04          # Constrained by high costs
    entertainment: 0.05    # Basic cultural participation
    miscellaneous: 0.06
    
  lower_middle:
    housing: 0.40          # Still high percentage
    food: 0.13
    transport: 0.13        # Mix of public/private transport
    utilities: 0.07
    healthcare: 0.06
    savings: 0.08          # Building emergency fund
    entertainment: 0.07    # Moderate cultural participation
    miscellaneous: 0.06
    
  middle:
    housing: 0.35          # NY middle class target
    food: 0.12
    transport: 0.12        # More flexible transport options
    utilities: 0.06
    healthcare: 0.05
    savings: 0.14          # Stronger savings capacity
    entertainment: 0.09    # Good cultural participation
    miscellaneous: 0.07
    
  upper_middle:
    housing: 0.32          # Premium housing options
    food: 0.10
    transport: 0.11
    utilities: 0.05
    healthcare: 0.05
    savings: 0.18          # Significant wealth building
    entertainment: 0.10    # Full cultural participation
    investments: 0.09      # Investment allocation
    
  high:
    housing: 0.28          # Luxury but optimized
    food: 0.08
    transport: 0.09        # Premium transport options
    utilities: 0.04
    healthcare: 0.04
    savings: 0.15          # Base savings
    entertainment: 0.12    # Premium cultural access
    investments: 0.16      # Major investment focus
    luxury: 0.04

# NY-specific behavioral economics patterns
behavioral_patterns:
  low:
    decision_time: immediate
    mental_accounting: [rent_utilities, food, everything_else]
    nudge_frequency: daily
    primary_motivators: [survival, stability]
    spending_volatility: high
    
  lower_middle:
    decision_time: hours_to_days  
    mental_accounting: [fixed_costs, food, transport, discretionary]
    nudge_frequency: weekly
    primary_motivators: [progress, peer_comparison]
    spending_volatility: moderate_high
    
  middle:
    decision_time: days_to_weeks
    mental_accounting: [housing, essentials, savings, lifestyle, emergency]
    nudge_frequency: bi_weekly
    primary_motivators: [optimization, lifestyle]
    spending_volatility: moderate
    
  upper_middle:
    decision_time: weeks_to_months
    mental_accounting: [housing, lifestyle, investments, taxes, emergency]
    nudge_frequency: monthly
    primary_motivators: [wealth_building, status]
    spending_volatility: low_moderate
    
  high:
    decision_time: months_to_years
    mental_accounting: [complex_portfolio_approach]
    nudge_frequency: quarterly
    primary_motivators: [wealth_preservation, legacy]
    spending_volatility: low

# Dynamic threshold modifiers for NY context
dynamic_modifiers:
  small_purchase_threshold_multiplier: 1.3    # Higher cost basis
  category_concentration_tolerance: 0.85      # More concentrated OK due to costs
  variance_threshold_adjustment: 1.2          # Higher variance expected
  impulse_buying_cost_adjustment: 1.4         # Higher cost basis for impulse buys
  emergency_fund_months_bonus: 1              # Add extra month due to high costs
  
# Regional financial stress factors
stress_factors:
  housing_burden_threshold: 0.50      # 50% housing burden triggers stress
  commute_cost_impact: 0.15           # 15% of income on commuting is high
  cost_of_living_pressure: 1.35       # High pressure factor
  
default_behavior: balanced
data_source: "US Census Bureau 2024, NY State Department of Labor"
last_updated: "2024-12-01"