currency: USD
region_code: US
region_name: United States (National Average)
cost_of_living_adjustment: 1.0
median_household_income: 70000   # 2024 US median
poverty_level: 15060            # Federal poverty guideline 2024

# Economically justified 5-tier thresholds (annual income)
# Based on US median household income and economic research
class_thresholds:
  low: 36000            # ~51% of US median (~$3,000/month)
  lower_middle: 57600   # ~82% of US median (~$4,800/month)
  middle: 86400         # ~123% of US median (~$7,200/month) 
  upper_middle: 144000  # ~206% of US median (~$12,000/month)
  # high: above upper_middle threshold

mandatory_categories: [housing, utilities, healthcare, debts, insurance]
seasonal_factors:
  winter:
    utilities: 1.2
    clothing: 1.15
  summer:
    travel: 1.3
    utilities: 0.9
classes:
  low:
    housing: 0.40          # Focus on affordable housing
    food: 0.15             # Budget-conscious food spending
    transport: 0.15        # Basic transportation needs
    utilities: 0.10
    healthcare: 0.08
    savings: 0.05          # Conservative savings goal
    entertainment: 0.04    # Limited discretionary
    miscellaneous: 0.03
    
  lower_middle:
    housing: 0.35          # Better housing options
    food: 0.13
    transport: 0.15
    utilities: 0.08
    healthcare: 0.07
    savings: 0.08          # Building emergency fund
    entertainment: 0.06
    miscellaneous: 0.08
    
  middle:
    housing: 0.30          # National average target
    food: 0.12
    transport: 0.15
    utilities: 0.07
    healthcare: 0.06
    savings: 0.12          # Significant savings rate
    entertainment: 0.08
    miscellaneous: 0.10
    
  upper_middle:
    housing: 0.28          # Premium housing efficient
    food: 0.10
    transport: 0.13
    utilities: 0.05
    healthcare: 0.05
    savings: 0.15          # Wealth building
    entertainment: 0.09
    investments: 0.10      # Investment allocation
    miscellaneous: 0.05
    
  high:
    housing: 0.25          # Luxury but optimized
    food: 0.08
    transport: 0.10
    utilities: 0.04
    healthcare: 0.04
    savings: 0.12          # Base savings
    entertainment: 0.10
    investments: 0.20      # Major investment focus
    luxury: 0.07

# Economic accuracy metadata
default_behavior: balanced