apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
  labels:
    name: external-secrets-system
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: external-secrets
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    # Financial compliance annotations
    compliance/framework: "SOX,PCI-DSS,GDPR"
    security/audit-required: "true"
    security/encryption-required: "true"