apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: external-secrets
  annotations:
    compliance/framework: "SOX,PCI-DSS,GDPR"
    security/provider: "aws-secrets-manager"
    security/encryption-required: "true"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: external-secrets
  annotations:
    compliance/framework: "SOX,PCI-DSS,GDPR"
    security/provider: "aws-parameter-store"
    security/encryption-required: "true"
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system

---
# Environment-specific secret stores for multi-environment support
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mita-staging-secrets
  namespace: mita-staging
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    environment: staging
  annotations:
    compliance/framework: "SOX,PCI-DSS,GDPR"
    security/environment: "staging"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mita-production-secrets
  namespace: mita-production
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    environment: production
  annotations:
    compliance/framework: "SOX,PCI-DSS,GDPR"
    security/environment: "production"
    security/criticality: "high"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system
  conditions:
    - namespaceSelector:
        matchLabels:
          name: mita-production
  retrySettings:
    maxRetries: 3
    retryInterval: 30s

---
# Disaster recovery secret store (different region)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-dr
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: external-secrets
  annotations:
    compliance/framework: "SOX,PCI-DSS,GDPR"
    security/provider: "aws-secrets-manager"
    security/purpose: "disaster-recovery"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2  # DR region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system

---
# Vault secret store (for hybrid cloud scenarios)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: external-secrets
  annotations:
    compliance/framework: "SOX,PCI-DSS,GDPR"
    security/provider: "hashicorp-vault"
spec:
  provider:
    vault:
      server: "https://vault.mita.finance:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system

---
# Configuration for secret store refresh and monitoring
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-config
  namespace: external-secrets-system
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: config
  annotations:
    compliance/framework: "SOX,PCI-DSS,GDPR"
data:
  # Refresh intervals based on secret criticality
  critical-secret-refresh-interval: "5m"
  high-secret-refresh-interval: "15m" 
  medium-secret-refresh-interval: "30m"
  low-secret-refresh-interval: "60m"
  
  # Retry configuration
  max-retry-attempts: "3"
  retry-backoff-duration: "30s"
  
  # Monitoring configuration
  metrics-enabled: "true"
  metrics-port: "8080"
  
  # Audit configuration
  audit-enabled: "true"
  audit-log-level: "info"
  
  # Security configuration
  tls-enabled: "true"
  webhook-port: "9443"
  
  # Compliance settings
  compliance-mode: "strict"
  audit-retention-days: "2555"  # 7 years for financial compliance