// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRI7k1ATHDbpi-KEpJCx8pgAufcF7WVKk',
    appId: '1:147595998708:android:84d48c2591631b948335a1',
    messagingSenderId: '147595998708',
    projectId: 'mita-finance',
    storageBucket: 'mita-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRI7k1ATHDbpi-KEpJCx8pgAufcF7WVKk',
    appId: '1:147595998708:ios:84d48c2591631b948335a1',
    messagingSenderId: '147595998708',
    projectId: 'mita-finance',
    storageBucket: 'mita-finance.firebasestorage.app',
    iosBundleId: 'mita.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRI7k1ATHDbpi-KEpJCx8pgAufcF7WVKk',
    appId: '1:147595998708:macos:84d48c2591631b948335a1',
    messagingSenderId: '147595998708',
    projectId: 'mita-finance',
    storageBucket: 'mita-finance.firebasestorage.app',
    iosBundleId: 'mita.finance',
  );
}
