// Integration test to inject JWT tokens into SecureStorage
// This test should be run ONCE to inject tokens, then the app can be restarted
//
// RUN: flutter test integration_test/inject_tokens_test.dart

import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:integration_test/integration_test.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('Inject JWT tokens into SecureStorage', (WidgetTester tester) async {
    // Initialize secure storage
    const storage = FlutterSecureStorage();

    // JWT tokens generated by /tmp/generate_jwt_tokens.py
    // User: test@mita.app (ID: 06224e8a-8fc3-46b0-9e9c-7ad94b1bdd0d)
    const accessToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjU4MTk1MjcsImlhdCI6MTc2NTgxMjMyNywibmJmIjoxNzY1ODEyMzI3LCJqdGkiOiI0NzVjOGY5Ni00Yzk3LTRhYWYtOTdlYi02ZGMxYTE2M2M1ODUiLCJpc3MiOiJtaXRhLWZpbmFuY2UtYXBpIiwiYXVkIjoibWl0YS1maW5hbmNlLWFwcCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZSI6InJlYWQ6cHJvZmlsZSB3cml0ZTpwcm9maWxlIHJlYWQ6dHJhbnNhY3Rpb25zIHdyaXRlOnRyYW5zYWN0aW9ucyByZWFkOmZpbmFuY2lhbF9kYXRhIHJlYWQ6YnVkZ2V0IHdyaXRlOmJ1ZGdldCByZWFkOmFuYWx5dGljcyIsInN1YiI6IjA2MjI0ZThhLThmYzMtNDZiMC05ZTljLTdhZDk0YjFiZGQwZCIsInVzZXJfaWQiOiIwNjIyNGU4YS04ZmMzLTQ2YjAtOWU5Yy03YWQ5NGIxYmRkMGQiLCJlbWFpbCI6InRlc3RAbWl0YS5hcHAifQ.YTXyxcD7ibuPvg30vH4xNOBWx0XvEhTWrWFrq1IQ0bU';

    const refreshToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjY0MTcxMjcsImlhdCI6MTc2NTgxMjMyNywibmJmIjoxNzY1ODEyMzI3LCJqdGkiOiI0OGUzOGU3OC03ZDkzLTQ5NjEtYTZmYS03NWEyOTUyMGU2MDkiLCJpc3MiOiJtaXRhLWZpbmFuY2UtYXBpIiwiYXVkIjoibWl0YS1maW5hbmNlLWFwcCIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwic2NvcGUiOiJyZWZyZXNoOnRva2VuIiwic3ViIjoiMDYyMjRlOGEtOGZjMy00NmIwLTllOWMtN2FkOTRiMWJkZDBkIiwidXNlcl9pZCI6IjA2MjI0ZThhLThmYzMtNDZiMC05ZTljLTdhZDk0YjFiZGQwZCJ9.aO-xJI02fewLKYdX-F7xd_hP0zEDqj2eALPQxdslie0';

    const userId = '06224e8a-8fc3-46b0-9e9c-7ad94b1bdd0d';

    print('=' * 60);
    print('Injecting JWT tokens into SecureStorage...');
    print('=' * 60);

    // Inject tokens into storage
    // Using the same keys as SecureTokenStorage service
    await storage.write(key: 'mita_access_token_v2', value: accessToken);
    await storage.write(key: 'mita_refresh_token_v2', value: refreshToken);
    await storage.write(key: 'mita_user_id_v2', value: userId);

    print('✅ JWT tokens injected successfully!');
    print('Access Token: ${accessToken.substring(0, 50)}...');
    print('Refresh Token: ${refreshToken.substring(0, 50)}...');
    print('User ID: $userId');
    print('');

    // Verify tokens were stored
    final storedAccessToken = await storage.read(key: 'mita_access_token_v2');
    final storedRefreshToken = await storage.read(key: 'mita_refresh_token_v2');
    final storedUserId = await storage.read(key: 'mita_user_id_v2');

    expect(storedAccessToken, accessToken);
    expect(storedRefreshToken, refreshToken);
    expect(storedUserId, userId);

    print('✅ Verification passed! Tokens stored correctly.');
    print('=' * 60);
    print('NEXT STEP: Restart the app to use these tokens.');
    print('Run: flutter run');
    print('=' * 60);
  });
}
